check secret

diff --git a/.github/workflows/deply-backend.yml b/.github/workflows/deply-backend.yml
--- a/.github/workflows/deply-backend.yml
+++ b/.github/workflows/deply-backend.yml
@@ -13,7 +13,24 @@ jobs:
           fetch-depth: 0
 
       - name: Check secrets
-        run: echo ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          if [
+            -z "${{ secrets.DOCKER_USERNAME }}"
+            -o -z "${{ secrets.DOCKER_PASSWORD }}"
+          ]; then
+            echo "Missing secrets! Please check your secrets."
+            exit 1
+          fi
+
+          if [
+            -z "${{ secrets.AWS_ACCESS_KEY_ID }}"
+            -o -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          ]; then
+            echo "Missing secrets! Please check your secrets."
+            exit 1
+          fi
+
+          ]
 
       - name: Docker login
         uses: docker/login-action@v3
